Pybo/models.py
from Pybo import db

class Question(db.Model):
    id = db.Column(db.Integer , primary_key=True)
    subject = db.Column(db.String(200) , nullable=False)
    content = db.Column(db.Text(),nullable=False)
    create_date = db.Column(db.DateTime(),nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    question_id = db.Column(db.Integer , db.ForeignKey('question.id' , ondelete='CASCADE'))
    question = db.relationship('Question' , backref=db.backref('answer_set'))
    content = db.Column(db.Text(),nullable=False)
    create_date = db.Column(db.DateTime(),nullable=False)

class Chatbot(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class User(db.Model):
   id = db.Column(db.Integer, primary_key=True)
   username = db.Column(db.String(150), unique=True, nullable=False)
   password = db.Column(db.String(200), nullable=False)
   email = db.Column(db.String(120),unique=True,nullable=False)

Pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField , PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import  DataRequired,Length,EqualTo,Email


class QuestionForm(FlaskForm):
    subject = StringField('제목' , validators=[DataRequired()])
    content = TextAreaField('내용', validators=[DataRequired()])

class AnswerForm(FlaskForm):
    content = TextAreaField('내용',validators=[DataRequired('내용은 필수입력 항목입니다.')])


class UserCreateForm(FlaskForm):
    username = StringField('사용자이름',validators=[DataRequired(),Length(min=3,max=25)])
    password1 = PasswordField('비밀번호' , validators=[DataRequired(),EqualTo('password2','비밀번호가 일치하지 않습니다.')])
    password2 = PasswordField('비밀번호', validators=[DataRequired()])
    email = EmailField('이메일',validators=[DataRequired(),Email()])


class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

Pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData

import config


naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()


app = Flask(__name__)
app.config.from_object(config)  #데이터베이스 설정
app.debug = True

        #ORM 데이터베이스 초기화
db.init_app(app)

if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app, db, render_as_batch=True)
else:
        migrate.init_app(app, db)


from .views import main_views,question_views,answer_views,auth_views
app.register_blueprint(main_views.bp)
app.register_blueprint(question_views.bp)
app.register_blueprint(answer_views.bp)
app.register_blueprint(auth_views.bp)


#필터등록
from .filter import format_datetime
app.jinja_env.filters['datetime'] = format_datetime

Pybo/views/answer_views.py
from flask import Blueprint , render_template , request, url_for
from Pybo import  db
from Pybo.models import Question,Answer
from datetime import datetime
from werkzeug.utils import redirect
from ..forms import AnswerForm

bp = Blueprint('answer',__name__,url_prefix='/answer')


@bp.route('/create/<int:question_id>' , methods = ('POST',))
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(question=question, content=content, create_date=datetime.now())
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('question.detail',question_id=question.id))

    return render_template('question/question_detail.html',question=question,form=form)

Pybo/views/auth_views.py
from flask import Blueprint, render_template, url_for, request, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from Pybo import  db
from Pybo.models import User
from Pybo.forms import UserCreateForm,UserLoginForm
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('auth',__name__,url_prefix='/auth')

@bp.before_app_request
def load_logged_in_user():

    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/signup/',methods=('GET','POST'))
def signup():
    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if not user:
            user = User(username=form.username.data,password=generate_password_hash(form.password1.data),email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')


    return render_template('/auth/signup.html',form=form)

@bp.route('/login/' , methods=('GET','POST'))
def login():

    form = UserLoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()

        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password , form.password.data ):
            error = '비밀번호가 올바르지 않습니다.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))

        flash(error)

    return render_template('/auth/login.html',form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

Pybo/views/main_views.py
from flask import Blueprint , render_template,url_for
from Pybo import  db
from Pybo.models import Question,Answer
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('main',__name__,url_prefix='/')


@bp.route('/')
def index():

    return redirect(url_for('question.qlist'))  #question 이라는 블루프린트에 qlist함수로 주소를 넘겨라




@bp.route('/test')
def test():
    for i in range(300):
        q = Question(subject='테스트 데이터입니다. {0}'.format(i) , content='내용무' , create_date=datetime.now())
        db.session.add(q)
    db.session.commit()
    return 'sucess'

Pybo/views/question_views.py
from flask import Blueprint , render_template, request, url_for
from werkzeug.utils import redirect
from Pybo import  db
from Pybo.models import Question,Answer
from datetime import datetime
from ..forms import QuestionForm,AnswerForm

bp = Blueprint('question',__name__,url_prefix='/question')

@bp.route('/list/')
def qlist():
    page = request.args.get('page',type=int,default=1)
    question_lst = Question.query.order_by(Question.create_date.desc())
    question_lst = question_lst.paginate( page , per_page=10)

    print(question_lst.total)
    print(question_lst.per_page)
    print(question_lst.iter_pages)
    print(question_lst.prev_num)


    return render_template('question/question_list.html', question_list=question_lst)

@bp.route('/detail/<int:question_id>/')    #<자료형:변수명>
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html',question = question , form=form)

@bp.route('/create/' , methods=('GET','POST'))

def create():
    form = QuestionForm()


    if request.method == "POST" and form.validate_on_submit():
        q = Question(subject=form.subject.data , content=form.content.data, create_date=datetime.now())
        db.session.add(q)
        db.session.commit()
        return redirect(url_for('main.index'))


    return render_template('question/question_form.html',form=form)

Pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <title>Pybo 입니다!</title>
</head>
<body>

<!-- ------------------------------ [edit] -------------------------------- -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">파이보</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <!------------------- 로그인이 되어있는 경우--------------------------------->
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('auth.logout')}}">{{ g.user.username}} (로그아웃)</a>
            </li>
        </ul>
        {% else %}


        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('auth.signup')}}">계정생성</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('auth.login')}}">로그인</a>
            </li>
        </ul>

        {% endif %}
    </div>
</nav>
<!-- ---------------------------------------------------------------------- -->



{% block content %}

{% endblock %}
</body>
</html>

Pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}" >

<div class="container my-3">
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{question.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date | datetime}}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{answer.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-1">
                    {{ answer.create_date | datetime}}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{url_for('answer.create',question_id=question.id)}}" method="post" class="my-3">
        <div class="form-group">
            {{ form.csrf_token }}

            {{ form.content.label }}
            {{ form.content(class='form-control') }}
        </div>
        <input type="submit" value="답변등록" class="btn btn-success">
    </form>

</div>

{% endblock %}

Pybo/templates/question/question_form.html
{% extends 'base.html' %}

{% block content %}




<div class="container">
    <h5 class="my-3 border-bottom pb-2"> 질문등록</h5>
    <form method="post" class="post-form my-3">
         {{ form.csrf_token }}

         {{ form.subject.label }}
         {{ form.subject(class='form-control') }}

         {{ form.content.label }}
         {{ form.content(class='form-control') }}

        <button type="submit" class="btn btn-primary my-2">저장하기</button>
    </form>
</div>
{% endblock %}

Pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css') }}">

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
                {% for question in question_list.items %}
                <tr>
                    <!-- 게시글 번호처리 -->
                    <td> {{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }} </td>
                    <td>
                        <a href="{{ url_for('question.detail',question_id=question.id) }}"> {{ question.subject}}  </a>

                        {% if question.answer_set|length > 0 %}
                            <span class="text-danger small ml-2">{{ question.answer_set|length }}</span>
                        {% endif %}
                    </td>
                    <td>
                        {{ question.create_date | datetime }}
                    </td>
                </tr>
                 {% endfor %}
            {% else %}
             <tr>
                 <td colspan="3">질문이 없습니다.</td>
             </tr>
             {% endif %}
        </tbody>
    </table>


    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->




    <a href="{{url_for('question.create')}}" class="btn btn-primary">질문 등록하기</a>
</div>

{% endblock %}

Pybo/templates/test.html
{% if age > 0 %}
    <p>나이가 0살보다 많습니다.</p>
{% else %}
    <p> 나이가 0살입니다.</p>
{% endif %}

{% for temp in listdata %}
    <p>{{ temp }}</p>
{% endfor %}